insert into DEPT (deptno, dname, loc) values (1, 'Engineering', 'Brodósqui');
insert into DEPT (deptno, dname, loc) values (2, 'Human Resources', 'Kiten');
insert into DEPT (deptno, dname, loc) values (3, 'Research and Development', 'Mpika');
insert into DEPT (deptno, dname, loc) values (4, 'Human Resources', 'Pankrushikha');
insert into DEPT (deptno, dname, loc) values (5, 'Services', 'Černovice');
insert into DEPT (deptno, dname, loc) values (6, 'Marketing', 'Goraj');
insert into DEPT (deptno, dname, loc) values (7, 'Sales', 'Bandar-e ‘Asalūyeh');
insert into DEPT (deptno, dname, loc) values (8, 'Business Development', 'Anchorage');
insert into DEPT (deptno, dname, loc) values (9, 'Research and Development', 'Lityn');
insert into DEPT (deptno, dname, loc) values (10, 'Sales', 'Drawsko Pomorskie');
insert into DEPT (deptno, dname, loc) values (11, 'Training', 'Banjar Tengah');
insert into DEPT (deptno, dname, loc) values (12, 'Sales', 'Gio Linh');
insert into DEPT (deptno, dname, loc) values (13, 'Training', 'San Jerónimo');
insert into DEPT (deptno, dname, loc) values (14, 'Sales', 'Reina Mercedes');
insert into DEPT (deptno, dname, loc) values (15, 'Legal', 'Barobo');
insert into DEPT (deptno, dname, loc) values (16, 'Services', 'Herne');
insert into DEPT (deptno, dname, loc) values (17, 'Research and Development', 'Suwangi Utara');
insert into DEPT (deptno, dname, loc) values (18, 'Product Management', 'Karangranjong');
insert into DEPT (deptno, dname, loc) values (19, 'Marketing', 'Ziroudani');
insert into DEPT (deptno, dname, loc) values (20, 'Engineering', 'Dengok');
insert into DEPT (deptno, dname, loc) values (21, 'Training', 'Talagasari');
insert into DEPT (deptno, dname, loc) values (22, 'Services', 'Mwinilunga');
insert into DEPT (deptno, dname, loc) values (23, 'Services', 'Tabalong');
insert into DEPT (deptno, dname, loc) values (24, 'Accounting', 'Kauswagan');
insert into DEPT (deptno, dname, loc) values (25, 'Support', 'Shelabolikha');
insert into DEPT (deptno, dname, loc) values (26, 'Engineering', 'Lampari');
insert into DEPT (deptno, dname, loc) values (27, 'Accounting', 'La Romana');
insert into DEPT (deptno, dname, loc) values (28, 'Product Management', 'Dolany');
insert into DEPT (deptno, dname, loc) values (29, 'Engineering', 'Valence');
insert into DEPT (deptno, dname, loc) values (30, 'Business Development', 'Nahuo');
insert into DEPT (deptno, dname, loc) values (31, 'Research and Development', 'Bernay');
insert into DEPT (deptno, dname, loc) values (32, 'Legal', 'Touama');
insert into DEPT (deptno, dname, loc) values (33, 'Research and Development', 'San Carlos');
insert into DEPT (deptno, dname, loc) values (34, 'Human Resources', 'Anwen');
insert into DEPT (deptno, dname, loc) values (35, 'Human Resources', 'Simnas');
insert into DEPT (deptno, dname, loc) values (36, 'Business Development', 'Pangantocan');
insert into DEPT (deptno, dname, loc) values (37, 'Marketing', 'Fuwen');
insert into DEPT (deptno, dname, loc) values (38, 'Research and Development', 'Fosca');
insert into DEPT (deptno, dname, loc) values (39, 'Product Management', 'Boljevac');
insert into DEPT (deptno, dname, loc) values (40, 'Research and Development', 'Tamanan');
insert into DEPT (deptno, dname, loc) values (41, 'Human Resources', 'Guleluke');
insert into DEPT (deptno, dname, loc) values (42, 'Training', 'Wangcun');
insert into DEPT (deptno, dname, loc) values (43, 'Human Resources', 'Yaransk');
insert into DEPT (deptno, dname, loc) values (44, 'Marketing', 'Antipino');
insert into DEPT (deptno, dname, loc) values (45, 'Product Management', 'Divichibazar');
insert into DEPT (deptno, dname, loc) values (46, 'Training', 'Foz do Arelho');
insert into DEPT (deptno, dname, loc) values (47, 'Human Resources', 'Telgawah');
insert into DEPT (deptno, dname, loc) values (48, 'Sales', 'Napenay');
insert into DEPT (deptno, dname, loc) values (49, 'Business Development', 'Firmat');
insert into DEPT (deptno, dname, loc) values (50, 'Training', 'Tibro');
insert into DEPT (deptno, dname, loc) values (51, 'Training', 'Cintawana');
insert into DEPT (deptno, dname, loc) values (52, 'Training', 'Koímisi');
insert into DEPT (deptno, dname, loc) values (53, 'Engineering', 'Jetak');
insert into DEPT (deptno, dname, loc) values (54, 'Legal', 'Bonao');
insert into DEPT (deptno, dname, loc) values (55, 'Business Development', 'Asamankese');
insert into DEPT (deptno, dname, loc) values (56, 'Services', 'São Gotardo');
insert into DEPT (deptno, dname, loc) values (57, 'Legal', 'Daping');
insert into DEPT (deptno, dname, loc) values (58, 'Product Management', 'Rostokino');
insert into DEPT (deptno, dname, loc) values (59, 'Support', 'Rangmanten');
insert into DEPT (deptno, dname, loc) values (60, 'Marketing', 'Coroatá');
insert into DEPT (deptno, dname, loc) values (61, 'Services', 'Puncaksempur');
insert into DEPT (deptno, dname, loc) values (62, 'Marketing', 'Strel''na');
insert into DEPT (deptno, dname, loc) values (63, 'Business Development', 'Alcalá');
insert into DEPT (deptno, dname, loc) values (64, 'Sales', 'Eisen');
insert into DEPT (deptno, dname, loc) values (65, 'Accounting', 'Doljo');
insert into DEPT (deptno, dname, loc) values (66, 'Legal', 'Magisterial');
insert into DEPT (deptno, dname, loc) values (67, 'Training', 'Vónitsa');
insert into DEPT (deptno, dname, loc) values (68, 'Marketing', 'Kimje');
insert into DEPT (deptno, dname, loc) values (69, 'Business Development', 'Jilib');
insert into DEPT (deptno, dname, loc) values (70, 'Sales', 'Barrancas');
insert into DEPT (deptno, dname, loc) values (71, 'Accounting', 'Manta');
insert into DEPT (deptno, dname, loc) values (72, 'Business Development', 'Sebedo');
insert into DEPT (deptno, dname, loc) values (73, 'Training', 'Łękawica');
insert into DEPT (deptno, dname, loc) values (74, 'Human Resources', 'Skarbimierz Osiedle');
insert into DEPT (deptno, dname, loc) values (75, 'Training', 'Taihe');
insert into DEPT (deptno, dname, loc) values (76, 'Services', 'Norcasia');
insert into DEPT (deptno, dname, loc) values (77, 'Research and Development', 'Kutacane');
insert into DEPT (deptno, dname, loc) values (78, 'Sales', 'Kos');
insert into DEPT (deptno, dname, loc) values (79, 'Business Development', 'Qorveh');
insert into DEPT (deptno, dname, loc) values (80, 'Business Development', 'Gaoxu');
insert into DEPT (deptno, dname, loc) values (81, 'Product Management', 'Tumpang Satu');
insert into DEPT (deptno, dname, loc) values (82, 'Services', 'Douma');
insert into DEPT (deptno, dname, loc) values (83, 'Business Development', 'Līvāni');
insert into DEPT (deptno, dname, loc) values (84, 'Accounting', 'Leskolovo');
insert into DEPT (deptno, dname, loc) values (85, 'Sales', 'Zhenzhushan');
insert into DEPT (deptno, dname, loc) values (86, 'Sales', 'Vangaindrano');
insert into DEPT (deptno, dname, loc) values (87, 'Legal', 'Allada');
insert into DEPT (deptno, dname, loc) values (88, 'Business Development', 'Terjan');
insert into DEPT (deptno, dname, loc) values (89, 'Accounting', 'Kiihtelysvaara');
insert into DEPT (deptno, dname, loc) values (90, 'Legal', 'Oskarshamn');
insert into DEPT (deptno, dname, loc) values (91, 'Support', 'Linëvo');
insert into DEPT (deptno, dname, loc) values (92, 'Engineering', 'Santa Monica');
insert into DEPT (deptno, dname, loc) values (93, 'Legal', 'Pervomays’k');
insert into DEPT (deptno, dname, loc) values (94, 'Business Development', 'Anse à Galets');
insert into DEPT (deptno, dname, loc) values (95, 'Support', 'Baon');
insert into DEPT (deptno, dname, loc) values (96, 'Business Development', 'Aston');
insert into DEPT (deptno, dname, loc) values (97, 'Marketing', 'Tío Pujio');
insert into DEPT (deptno, dname, loc) values (98, 'Legal', 'Khueang Nai');
insert into DEPT (deptno, dname, loc) values (99, 'Sales', 'Ilha de Moçambique');
insert into DEPT (deptno, dname, loc) values (100, 'Accounting', 'Sukoanyar');
